import { Moon, Settings2, ShieldCheck, Sun } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { ToolHeader } from "../tool-header";
import { useAuth, type Tone } from "@/lib/auth-context";
import { cn } from "@/lib/utils";
import { useEffect, useState } from "react";

const TONES: Tone[] = ["Formal", "Friendly", "Persuasive", "Empathetic"];

export function SettingsView() {
  const { profile, user, updateProfile, signOut } = useAuth();
  const [name, setName] = useState(profile?.display_name ?? "");

  useEffect(() => {
    if (profile?.display_name) setName(profile.display_name);
  }, [profile?.display_name]);

  return (
    <div className="space-y-6">
      <ToolHeader
        icon={Settings2}
        eyebrow="Settings"
        title="Make nomi feel like yours"
        description="Small preferences that make each session calmer. Everything is stored privately to your account."
      />

      <div className="grid gap-5 xl:grid-cols-2">
        <section className="glass-panel space-y-5 rounded-3xl p-5">
          <div className="space-y-2">
            <Label htmlFor="display-name">Display name</Label>
            <div className="flex gap-2">
              <Input
                id="display-name"
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="Alex"
              />
              <Button
                variant="secondary"
                className="rounded-full"
                onClick={() => void updateProfile({ display_name: name.trim() || "there" })}
              >
                Save
              </Button>
            </div>
            <p className="text-xs text-muted-foreground">{user?.email}</p>
          </div>

          <div className="space-y-2">
            <Label>Default tone</Label>
            <div className="flex flex-wrap gap-2">
              {TONES.map((tone) => (
                <button
                  key={tone}
                  type="button"
                  onClick={() => void updateProfile({ preferred_tone: tone })}
                  className={cn(
                    "rounded-full border px-3.5 py-1.5 text-sm transition-all duration-200 hover:scale-[1.03]",
                    profile?.preferred_tone === tone
                      ? "border-transparent bg-primary text-primary-foreground shadow-glass"
                      : "border-border/70 bg-background/50 text-muted-foreground hover:border-primary/40 hover:text-foreground",
                  )}
                >
                  {tone}
                </button>
              ))}
            </div>
            <p className="text-xs text-muted-foreground">
              Used as the starting tone in the Email Composer.
            </p>
          </div>

          <div className="flex items-center justify-between rounded-2xl border border-border/60 bg-background/50 px-4 py-3">
            <div className="flex items-center gap-3">
              {profile?.dark_mode ? (
                <Moon className="size-[1.15rem] text-primary" />
              ) : (
                <Sun className="size-[1.15rem] text-primary" />
              )}
              <div>
                <p className="text-sm font-medium">Dark mode</p>
                <p className="text-xs text-muted-foreground">A softer look after hours.</p>
              </div>
            </div>
            <Switch
              checked={Boolean(profile?.dark_mode)}
              onCheckedChange={(checked) => void updateProfile({ dark_mode: checked })}
              aria-label="Toggle dark mode"
            />
          </div>

          <Button variant="ghost" className="rounded-full" onClick={() => void signOut()}>
            Sign out
          </Button>
        </section>

        <section className="glass-panel space-y-3 rounded-3xl p-5">
          <div className="flex items-center gap-3">
            <span className="grid size-10 place-items-center rounded-2xl bg-teal/15 text-teal">
              <ShieldCheck className="size-5" />
            </span>
            <h3 className="font-semibold">Responsible AI</h3>
          </div>
          <p className="text-sm leading-relaxed text-muted-foreground">
            nomi produces suggestions generated by AI models. Outputs can be incomplete,
            outdated or simply wrong, and are never a substitute for your judgement or for
            professional, legal, financial or HR advice.
          </p>
          <p className="text-sm leading-relaxed text-muted-foreground">
            Always review before sending, sharing or acting on a draft. Avoid entering
            confidential or personal data you wouldn't put in a shared document. Nothing is
            ever sent, scheduled or shared on your behalf — you stay the author.
          </p>
        </section>
      </div>
    </div>
  );
}
